master:
    image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
    command: /bin/bash -c "service ssh start"
slave1:
    image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
    command: /bin/bash -c "sed -i \"s/server171/{{master}}/g\" /root/hadoop-2.3.0/etc/hadoop/slaves"
slave2:
    image: docker.iwanna.xyz:5000/hmonkey/mpi:v1
    command: /bin/bash -c "sed -i \"s/server171/{{master}}/g\" /root/hadoop-2.3.0/etc/hadoop/slaves "
